slogo_team02: view.KeyControls Class Reference
view.KeyControls Class Reference
Public Member Functions
KeyControls (SlogoModel model, BorderPane window) throws InvalidArgumentsException
void makeKeyCommands ()
Private Member Functions
void setCommandsList ()
void setKeyMap () throws InvalidArgumentsException
Private Attributes
List< String > keyCommands = new ArrayList<String>()
SlogoModel myModel
BorderPane myWindow
Locale myLocale
Map< KeyCode, Instruction > keyMap = new HashMap<KeyCode, Instruction>()
Static Private Attributes
static final long serialVersionUID = -6381483434400107432L
static final String DEFAULT_LANGUAGE_PACKAGE = "resources.languages/"
Detailed Description
Take in key W,S,A,D,X as the key to move the turtle forward, backward, left, right and set the turtle's head straight upward.
Author
Mengen Huang
Kevin Li
Definition at line 29 of file KeyControls.java.
Constructor & Destructor Documentation
view.KeyControls.KeyControls (SlogoModel model, BorderPane window) throws InvalidArgumentsException
Create the KeyControl.
Parameters
model model run in the window
window window shown on the screen
Definition at line 47 of file KeyControls.java.
References view.KeyControls.makeKeyCommands(), view.KeyControls.setCommandsList(), and view.KeyControls.setKeyMap().
Member Function Documentation
void view.KeyControls.makeKeyCommands ()
Once a key is pushed, the corresponding event is triggered so that the turtle will move according to the keys pressed.
Definition at line 90 of file KeyControls.java.
References instructions.ParameterInstruction.addParam(), model.CommandsList.contains(), model.ObservableData.get(), model.CommandsList.get(), model.SlogoModel.getMyData(), and model.SlogoModel.parseAndExecute().
Referenced by view.KeyControls.KeyControls().
void view.KeyControls.setCommandsList () private
get the commands in different language to move forward, backward, left, right and setheading.
Definition at line 61 of file KeyControls.java.
Referenced by view.KeyControls.KeyControls().
void view.KeyControls.setKeyMap () throws InvalidArgumentsException private
Set up the keyMap. Match the Keycode with the specific commands.
Definition at line 77 of file KeyControls.java.
References model.SlogoModel.getParser(), and parser.Parser.parse().
Referenced by view.KeyControls.KeyControls().
Member Data Documentation
final String view.KeyControls.DEFAULT_LANGUAGE_PACKAGE = "resources.languages/" static private
Definition at line 33 of file KeyControls.java.
List<String> view.KeyControls.keyCommands = new ArrayList<String>() private
Definition at line 35 of file KeyControls.java.
Map<KeyCode, Instruction> view.KeyControls.keyMap = new HashMap<KeyCode, Instruction>() private
Definition at line 39 of file KeyControls.java.
Locale view.KeyControls.myLocale private
Definition at line 38 of file KeyControls.java.
SlogoModel view.KeyControls.myModel private
Definition at line 36 of file KeyControls.java.
BorderPane view.KeyControls.myWindow private
Definition at line 37 of file KeyControls.java.
final long view.KeyControls.serialVersionUID = -6381483434400107432L static private
Definition at line 32 of file KeyControls.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/KeyControls.java