slogo_team02: instructions.ListInstruction Class Reference
instructions.ListInstruction Class Reference
Public Member Functions
ListInstruction (List< Instruction > lst)
List< Instruction > getInstructionList ()
double execute (ObservableData od) throws InvalidArgumentsException
Public Member Functions inherited from instructions.ZeroParamInstruction
int getNumParams ()
void addParam (Instruction param)
Private Attributes
List< Instruction > myInstructionList = new ArrayList<Instruction>()
Static Private Attributes
static final long serialVersionUID = 8768754397704316762L
Detailed Description
This represents the super class for instructions with lists
Author
Sandy Lee
Definition at line 16 of file ListInstruction.java.
Constructor & Destructor Documentation
instructions.ListInstruction.ListInstruction (List< Instruction > lst)
Constructor for list instruction
Parameters
lst of instructions
Definition at line 27 of file ListInstruction.java.
Member Function Documentation
double instructions.ListInstruction.execute (ObservableData data) throws InvalidArgumentsException
Executes the functionality of the instruction to change data in the program, such as lists of history and scene nodes during drawing.
Returns
Double value of the expression
Parameters
data of observables
Exceptions
InvalidArgumentsException throws when there is an argument error.
Implements instructions.Instruction.
Definition at line 39 of file ListInstruction.java.
List<Instruction> instructions.ListInstruction.getInstructionList ()
Returns
list of instructions
Definition at line 34 of file ListInstruction.java.
References instructions.ListInstruction.myInstructionList.
Referenced by instructions.commands.DoTimes.execute(), instructions.commands.MakeUserInstruction.execute(), and instructions.commands.Tell.getAskedIDs().
Member Data Documentation
List<Instruction> instructions.ListInstruction.myInstructionList = new ArrayList<Instruction>() private
Definition at line 19 of file ListInstruction.java.
Referenced by instructions.ListInstruction.getInstructionList().
final long instructions.ListInstruction.serialVersionUID = 8768754397704316762L static private
Definition at line 18 of file ListInstruction.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/instructions/ListInstruction.java