slogo_team02: instructions.UserDefinedCommand Class Reference
instructions.UserDefinedCommand Class Reference
Public Member Functions
UserDefinedCommand (String name)
UserDefinedCommand (UserDefinedCommand udcommand)
void defineFunction (List< Instruction > variables, Instruction commands)
double execute (ObservableData data) throws InvalidArgumentsException
Public Member Functions inherited from instructions.UserDefinedInstruction
UserDefinedInstruction (String name)
String getName ()
Public Member Functions inherited from instructions.ParameterInstruction
int getNumParams ()
void addParam (Instruction param)
Private Member Functions
void setVariables (VariablesList varList, ObservableData data) throws InvalidArgumentsException
Private Attributes
List< Instruction > myVariables
Instruction myCommands
Static Private Attributes
static final long serialVersionUID = 241936480193090236L
Additional Inherited Members
Protected Member Functions inherited from instructions.ParameterInstruction
ParameterInstruction ()
Protected Attributes inherited from instructions.UserDefinedInstruction
String myName
Protected Attributes inherited from instructions.ParameterInstruction
int myNumParams
List< Instruction > myParams
Detailed Description
Class to create user defined commands.
Author
Jennie Ju
Definition at line 17 of file UserDefinedCommand.java.
Constructor & Destructor Documentation
instructions.UserDefinedCommand.UserDefinedCommand (String name)
Parameters
name
Definition at line 26 of file UserDefinedCommand.java.
instructions.UserDefinedCommand.UserDefinedCommand (UserDefinedCommand udcommand)
Parameters
udcommand user defined command
Definition at line 33 of file UserDefinedCommand.java.
References instructions.UserDefinedCommand.defineFunction(), instructions.UserDefinedCommand.myCommands, instructions.UserDefinedInstruction.myName, and instructions.UserDefinedCommand.myVariables.
Member Function Documentation
void instructions.UserDefinedCommand.defineFunction (List< Instruction > variables, Instruction commands)
Parameters
variables for user defined command
commands for the defined command
Definition at line 42 of file UserDefinedCommand.java.
Referenced by instructions.commands.MakeUserInstruction.execute(), and instructions.UserDefinedCommand.UserDefinedCommand().
double instructions.UserDefinedCommand.execute (ObservableData data) throws InvalidArgumentsException
Executes the functionality of the instruction to change data in the program, such as lists of history and scene nodes during drawing.
Returns
Double value of the expression
Parameters
data of observables
Exceptions
InvalidArgumentsException throws when there is an argument error.
Implements instructions.Instruction.
Definition at line 49 of file UserDefinedCommand.java.
References model.VariablesList.addScope(), instructions.Instruction.execute(), model.VariablesList.get(), model.VariablesList.removeScope(), and instructions.UserDefinedCommand.setVariables().
void instructions.UserDefinedCommand.setVariables (VariablesList varList, ObservableData data) throws InvalidArgumentsException private
Parameters
varList that contains all of the defined variables
data of observables
Exceptions
InvalidArgumentsException throws when there is not enough parameters
Definition at line 72 of file UserDefinedCommand.java.
References instructions.UserDefinedInstruction.getName(), and instructions.ParameterInstruction.myParams.
Referenced by instructions.UserDefinedCommand.execute().
Member Data Documentation
Instruction instructions.UserDefinedCommand.myCommands private
Definition at line 21 of file UserDefinedCommand.java.
Referenced by instructions.UserDefinedCommand.UserDefinedCommand().
List<Instruction> instructions.UserDefinedCommand.myVariables private
Definition at line 20 of file UserDefinedCommand.java.
Referenced by instructions.UserDefinedCommand.UserDefinedCommand().
final long instructions.UserDefinedCommand.serialVersionUID = 241936480193090236L static private
Definition at line 19 of file UserDefinedCommand.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/instructions/UserDefinedCommand.java