slogo_team02: view.DataView Class Reference
view.DataView Class Reference
Public Member Functions
DataView (InputView input, double width, double height, Locale locale)
void update (CommandsList commandsList, VariablesList variablesList)
Public Member Functions inherited from view.PaneView
void setView (double width, double height)
Private Attributes
BasicCommandsView myBasicCommands
UDCommandsView myUDCommands
VariablesView myVariablesView
Accordion myView
Locale myLocale
Static Private Attributes
static final String DEFAULT_DISPLAY_RESOURCE = "resources.languages/Display"
static final double WIDTH_RATIO =0.2
static final double HEIGHT_RATIO =0.6875
Detailed Description
The visual component that puts all three types of views - variables, user defined commands, and basic commands into an Accordian.
Author
Kevin Li
Meng'en Huang
Definition at line 17 of file DataView.java.
Constructor & Destructor Documentation
view.DataView.DataView (InputView input, double width, double height, Locale locale)
Definition at line 29 of file DataView.java.
References view.DataView.myBasicCommands, view.DataView.myUDCommands, view.DataView.myVariablesView, and view.PaneView.setView().
Member Function Documentation
void view.DataView.update (CommandsList commandsList, VariablesList variablesList)
Updates the view using model's commandsList and variablesList data. Calls the respective update function in the subcomponents.
Parameters
commandsList List of all the commands - user defined and basic.
variablesList List of all the user defined variables.
Definition at line 61 of file DataView.java.
References view.VariablesView.update(), view.BasicCommandsView.update(), and view.UDCommandsView.update().
Referenced by view.SlogoWindow.update().
Member Data Documentation
final String view.DataView.DEFAULT_DISPLAY_RESOURCE = "resources.languages/Display" static private
Definition at line 19 of file DataView.java.
final double view.DataView.HEIGHT_RATIO =0.6875 static private
Definition at line 21 of file DataView.java.
BasicCommandsView view.DataView.myBasicCommands private
Definition at line 23 of file DataView.java.
Referenced by view.DataView.DataView().
Locale view.DataView.myLocale private
Definition at line 27 of file DataView.java.
UDCommandsView view.DataView.myUDCommands private
Definition at line 24 of file DataView.java.
Referenced by view.DataView.DataView().
VariablesView view.DataView.myVariablesView private
Definition at line 25 of file DataView.java.
Referenced by view.DataView.DataView().
Accordion view.DataView.myView private
Definition at line 26 of file DataView.java.
final double view.DataView.WIDTH_RATIO =0.2 static private
Definition at line 20 of file DataView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/DataView.java