slogo_team02: model.TurtlesList Class Reference
model.TurtlesList Class Reference
Public Member Functions
TurtlesList ()
double getNumTurtles ()
void addTurtle ()
void addScope (List< Integer > active)
void removeScope ()
void setActive (List< Integer > active)
void setInactive (List< Integer > inactive)
double getActiveID ()
void clear ()
void remove (Object n)
Private Attributes
List< Turtle > allTurtles
List< Integer > activeIDs
Stack< List< Integer > > turtleScope
Static Private Attributes
static final long serialVersionUID = 7316151669215320429L
Detailed Description
The list of turtles representing multiple turtles in one tab.
Author
Kevin Li
Definition at line 12 of file TurtlesList.java.
Constructor & Destructor Documentation
model.TurtlesList.TurtlesList ()
Instantiate the turtlesList.
Definition at line 22 of file TurtlesList.java.
References model.TurtlesList.addTurtle().
Member Function Documentation
void model.TurtlesList.addScope (List< Integer > active)
Add active turtles to the scope.
Parameters
active
Definition at line 49 of file TurtlesList.java.
References model.TurtlesList.setActive().
Referenced by instructions.commands.Ask.execute().
void model.TurtlesList.addTurtle ()
Add in turtle in the list.
Definition at line 40 of file TurtlesList.java.
Referenced by model.TurtlesList.clear(), and model.TurtlesList.TurtlesList().
void model.TurtlesList.clear ()
Clear and initiate the turtle list.
Implements model.Feature.
Definition at line 89 of file TurtlesList.java.
References model.TurtlesList.addTurtle().
double model.TurtlesList.getActiveID ()
Get the active ID of the turtle.
Returns
the ID of the active turtle
Definition at line 81 of file TurtlesList.java.
Referenced by instructions.commands.ID.execute().
double model.TurtlesList.getNumTurtles ()
Get the number of the turtles in the list.
Returns
number of the turtles in the list
Definition at line 33 of file TurtlesList.java.
Referenced by instructions.commands.NumTurtles.execute().
void model.TurtlesList.remove (Object o)
Shared method that remove a specific object from the model.
Parameters
o the object to be removed
Exceptions
InvalidArgumentsException
Implements model.Feature.
Definition at line 96 of file TurtlesList.java.
void model.TurtlesList.removeScope ()
Remove turtle in the turtleScop.
Definition at line 57 of file TurtlesList.java.
Referenced by instructions.commands.Ask.execute().
void model.TurtlesList.setActive (List< Integer > active)
Set the active turtle list.
Parameters
active list of active turtle's ID
Definition at line 65 of file TurtlesList.java.
Referenced by model.TurtlesList.addScope(), and instructions.commands.Tell.execute().
void model.TurtlesList.setInactive (List< Integer > inactive)
Set the turtles inactive.
Parameters
inactive list of inactive turtles
Definition at line 73 of file TurtlesList.java.
Member Data Documentation
List<Integer> model.TurtlesList.activeIDs private
Definition at line 16 of file TurtlesList.java.
List<Turtle> model.TurtlesList.allTurtles private
Definition at line 15 of file TurtlesList.java.
final long model.TurtlesList.serialVersionUID = 7316151669215320429L static private
Definition at line 14 of file TurtlesList.java.
Stack<List<Integer> > model.TurtlesList.turtleScope private
Definition at line 17 of file TurtlesList.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/model/TurtlesList.java