slogo_team02: view.SlogoView Class Reference
view.SlogoView Class Reference
Public Member Functions
SlogoView (Stage stage, Locale locale, double width, double height)
Scene generateScene ()
Private Member Functions
void setTabView (double width, double height)
Private Attributes
Scene myScene
BorderPane myRoot
TabPane myTabs
Static Private Attributes
static final double HEIGHT_RATIO = 0.95
Detailed Description
The over-arching view contains menuView and multiple SlogoWindows.
Author
Mengen Huang
Kevin Li
Definition at line 15 of file SlogoView.java.
Constructor & Destructor Documentation
view.SlogoView.SlogoView (Stage stage, Locale locale, double width, double height)
Create the SlogoView.
Parameters
stage
locale language and locale used in SlogoView
width width of View
height height of View
Definition at line 28 of file SlogoView.java.
References view.SlogoView.setTabView().
Member Function Documentation
Scene view.SlogoView.generateScene ()
Definition at line 44 of file SlogoView.java.
References view.SlogoView.myScene.
Referenced by main.Main.start().
void view.SlogoView.setTabView (double width, double height) private
Definition at line 38 of file SlogoView.java.
Referenced by view.SlogoView.SlogoView().
Member Data Documentation
final double view.SlogoView.HEIGHT_RATIO = 0.95 static private
Definition at line 16 of file SlogoView.java.
BorderPane view.SlogoView.myRoot private
Definition at line 18 of file SlogoView.java.
Scene view.SlogoView.myScene private
Definition at line 17 of file SlogoView.java.
Referenced by view.SlogoView.generateScene().
TabPane view.SlogoView.myTabs private
Definition at line 19 of file SlogoView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/SlogoView.java