slogo_team02: instructions.commands.ShowTurtle Class Reference
instructions.commands.ShowTurtle Class Reference
Public Member Functions
double execute (ObservableData data)
int getNumParams ()
void addParam (Instruction param)
Static Private Attributes
static final long serialVersionUID = 7056907549306719588L
Detailed Description
implements showturtle command shows the turtle on the screen
Author
Sandy Lee
Definition at line 15 of file ShowTurtle.java.
Member Function Documentation
void instructions.commands.ShowTurtle.addParam (Instruction param)
Adds an instruction to the list of parameters for the instruction
Parameters
param Instruction used as a parameter in the instruction
Implements instructions.Instruction.
Definition at line 33 of file ShowTurtle.java.
double instructions.commands.ShowTurtle.execute (ObservableData data)
Executes the functionality of the instruction to change data in the program, such as lists of history and scene nodes during drawing.
Returns
Double value of the expression
Parameters
data of observables
Exceptions
InvalidArgumentsException throws when there is an argument error.
Implements instructions.Instruction.
Definition at line 20 of file ShowTurtle.java.
References model.Turtle.getDrawing(), model.ObservableData.getTurtle(), model.Turtle.getTurtleImg(), and model.Turtle.setVisible().
int instructions.commands.ShowTurtle.getNumParams ()
Gets the number of parameters used in the instruction, Used in the parser when evaluating different types of instructions with various numbers of parameters
Returns
int number of parameters
Implements instructions.Instruction.
Definition at line 28 of file ShowTurtle.java.
Member Data Documentation
final long instructions.commands.ShowTurtle.serialVersionUID = 7056907549306719588L static private
Definition at line 17 of file ShowTurtle.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/instructions/commands/ShowTurtle.java