slogo_team02: parser.InstructionFactory Class Reference
parser.InstructionFactory Class Reference
Public Member Functions
InstructionFactory (ObservableData data)
Instruction makeInstruction (String type)
Static Public Attributes
static final String CHINESE_REGEX = "[\u4e00-\u9fa5]+(\\?)?"
Private Member Functions
ResourceBundle loadResourceBundle (String filepath)
Private Attributes
ResourceBundle myLanguageBundle
ObservableData myData
Static Private Attributes
static final long serialVersionUID = -2129488091762474882L
static final String CONSTANT_REGEX = "-?[0-9]+\\.?[0-9]*"
static final String VARIABLE_REGEX = ":[a-zA-z]+"
static final String COMMAND_REGEX = "[a-zA-Z_]+(\\?)?"
Detailed Description
Factory design pattern for creating instances of different instructions
Author
Jennie Ju
Definition at line 19 of file InstructionFactory.java.
Constructor & Destructor Documentation
parser.InstructionFactory.InstructionFactory (ObservableData data)
Parameters
data of observables
Definition at line 32 of file InstructionFactory.java.
References parser.InstructionFactory.loadResourceBundle().
Member Function Documentation
ResourceBundle parser.InstructionFactory.loadResourceBundle (String filepath) private
Parameters
filepath for the resource bundle
Returns
resource bundle
Definition at line 42 of file InstructionFactory.java.
Referenced by parser.InstructionFactory.InstructionFactory().
Instruction parser.InstructionFactory.makeInstruction (String type)
Takes a string type of instruction and instantiates the class based on the type
Parameters
type String name of type of instruction
Returns
Instruction class of that type
Definition at line 53 of file InstructionFactory.java.
References model.ObservableData.get(), and model.CommandsList.get().
Referenced by parser.Parser.parseTokens().
Member Data Documentation
final String parser.InstructionFactory.CHINESE_REGEX = "[\u4e00-\u9fa5]+(\\?)?" static
Definition at line 24 of file InstructionFactory.java.
final String parser.InstructionFactory.COMMAND_REGEX = "[a-zA-Z_]+(\\?)?" static private
Definition at line 23 of file InstructionFactory.java.
final String parser.InstructionFactory.CONSTANT_REGEX = "-?[0-9]+\\.?[0-9]*" static private
Definition at line 21 of file InstructionFactory.java.
ObservableData parser.InstructionFactory.myData private
Definition at line 27 of file InstructionFactory.java.
ResourceBundle parser.InstructionFactory.myLanguageBundle private
Definition at line 25 of file InstructionFactory.java.
final long parser.InstructionFactory.serialVersionUID = -2129488091762474882L static private
Definition at line 20 of file InstructionFactory.java.
final String parser.InstructionFactory.VARIABLE_REGEX = ":[a-zA-z]+" static private
Definition at line 22 of file InstructionFactory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/parser/InstructionFactory.java