slogo_team02: model.CommandsList Class Reference
model.CommandsList Class Reference
Public Member Functions
CommandsList (Locale locale)
void add (String commandSyntax, UserDefinedCommand userDefinedCom)
void delete (String commandSyntax)
Instruction get (String commandSyntax)
boolean contains (String commandSyntax)
void changeLanguage (String language)
List< String > getCommandSyntaxes ()
void clear ()
void remove (Object commandSyntax)
List< String[]> generate ()
Private Member Functions
ResourceBundle loadResourceBundle (String filepath)
Map< String, String > initCommandsMap (Set< String > keys, ResourceBundle bundle)
List< String > makeCommandsList ()
Private Attributes
ResourceBundle languageBundle
ResourceBundle commandsBundle
Map< String, String > preDefCommandTypes
Map< String, String > preDefCommandSyntaxes
Map< String, UserDefinedCommand > userDefCommands
Static Private Attributes
static final long serialVersionUID = -4687405266966458965L
static final String DEFAULT_LANGUAGE_PACKAGE
static final String PRE_DEFINED_COMMANDS_RESOURCE
Detailed Description
CommandsList class. Contains the list of pre-defined and user-defined commands. Class is to be accessed by the commands AND by the instruction factory.
Author
slogo_team02 a.k.a. TEAM ROCKET
Mengen Huang
Kevin Li
Jennie Ju
Sandy Lee
Definition at line 27 of file CommandsList.java.
Constructor & Destructor Documentation
model.CommandsList.CommandsList (Locale locale)
Pre-difined and user-defined lists of commands stored in map.
Parameters
locale language and locale of the window
Definition at line 45 of file CommandsList.java.
References model.CommandsList.commandsBundle, model.CommandsList.initCommandsMap(), model.CommandsList.languageBundle, and model.CommandsList.loadResourceBundle().
Member Function Documentation
void model.CommandsList.add (String commandSyntax, UserDefinedCommand userDefinedCom)
Add in new user-defined commands into UserDefined commands map.
Parameters
commandSyntax name of the user-defined command
userDefinedCom The commands to do after calling the name
Definition at line 93 of file CommandsList.java.
Referenced by instructions.commands.MakeUserInstruction.execute().
void model.CommandsList.changeLanguage (String language)
Allows switching of language.
Parameters
language string of language to change to
Definition at line 145 of file CommandsList.java.
References model.CommandsList.loadResourceBundle().
void model.CommandsList.clear ()
Clear the user-defined commands map.
Implements model.Feature.
Definition at line 164 of file CommandsList.java.
boolean model.CommandsList.contains (String commandSyntax)
Check if either predefined commands map or user-defined commands map. contains the command
Parameters
commandSyntax name of the command to be checked
Returns
if the command is contained in either commands map
Definition at line 136 of file CommandsList.java.
Referenced by view.KeyControls.makeKeyCommands().
void model.CommandsList.delete (String commandSyntax)
Delete the user-defined command from the user-defiend commands map.
Parameters
commandSyntax the name of the user-defined command to be deleted
Definition at line 102 of file CommandsList.java.
List<String[]> model.CommandsList.generate ()
Generate a list of two string arrays to pass to the front-end view package.
Returns
a list of two string arrays: predefined commands name array and user-defined commands name array
Definition at line 185 of file CommandsList.java.
References model.CommandsList.makeCommandsList().
Referenced by view.BasicCommandsView.update(), and view.UDCommandsView.update().
Instruction model.CommandsList.get (String commandSyntax)
Get the instruction which matches the name of the user-defined command.
Parameters
commandSyntax name of the user-defined command
Returns
instruction which matches the name of the user-defined command
Definition at line 115 of file CommandsList.java.
Referenced by instructions.commands.MakeUserInstruction.execute(), parser.InstructionFactory.makeInstruction(), and view.KeyControls.makeKeyCommands().
List<String> model.CommandsList.getCommandSyntaxes ()
Get all the names of predefined commands and user-defined commands.
Returns
names of commands in a list
Definition at line 153 of file CommandsList.java.
Map<String, String> model.CommandsList.initCommandsMap (Set< String > keys, ResourceBundle bundle) private
Create the commands map according to the information. stored in ResourceBundle.
Parameters
keys ResourceBundle keySet
bundle ResrouceBundle to load
Returns
map where all the values in ResourceBundle as keys and KeySet of ResourceBundle as values
Definition at line 74 of file CommandsList.java.
Referenced by model.CommandsList.CommandsList().
ResourceBundle model.CommandsList.loadResourceBundle (String filepath) private
Get the ResourceBundle according to file path.
Parameters
filepath path to get the resource
Returns
ResourceBundle
Definition at line 62 of file CommandsList.java.
Referenced by model.CommandsList.changeLanguage(), and model.CommandsList.CommandsList().
List<String> model.CommandsList.makeCommandsList () private
Make a list of predefined commands which group commands of same function. together. Fix the random distribution of commands in the map.
Returns
a list of sorted commands according to their functions
Definition at line 200 of file CommandsList.java.
Referenced by model.CommandsList.generate().
void model.CommandsList.remove (Object commandSyntax)
Remove a user-defined command from the map. Indicate when the required command name is not found in the map.
Implements model.Feature.
Definition at line 173 of file CommandsList.java.
Member Data Documentation
ResourceBundle model.CommandsList.commandsBundle private
Definition at line 35 of file CommandsList.java.
Referenced by model.CommandsList.CommandsList().
final String model.CommandsList.DEFAULT_LANGUAGE_PACKAGE static private
Initial value:
=
                                                "resources.languages/"
Definition at line 30 of file CommandsList.java.
ResourceBundle model.CommandsList.languageBundle private
Definition at line 34 of file CommandsList.java.
Referenced by model.CommandsList.CommandsList().
final String model.CommandsList.PRE_DEFINED_COMMANDS_RESOURCE static private
Initial value:
=
                                    "resources.parsing/PreDefinedCommands"
Definition at line 32 of file CommandsList.java.
Map<String, String> model.CommandsList.preDefCommandSyntaxes private
Definition at line 38 of file CommandsList.java.
Map<String, String> model.CommandsList.preDefCommandTypes private
Definition at line 37 of file CommandsList.java.
final long model.CommandsList.serialVersionUID = -4687405266966458965L static private
Definition at line 29 of file CommandsList.java.
Map<String, UserDefinedCommand> model.CommandsList.userDefCommands private
Definition at line 39 of file CommandsList.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/model/CommandsList.java