slogo_team02: model.Pen Class Reference
model.Pen Class Reference
Public Member Functions
Pen ()
void setCustom (List< Color > custom)
void setStrokeWidth (double width)
void setPenColor (Color color)
void setPenDown (boolean state)
double isPenDown ()
Color getPenColor ()
Line drawLine (double[] start, double[] end)
Line createLine (double[] start, double[] end, Color color)
List< Color > getCustom ()
void clear ()
void changeLineProperty (String properties)
Private Attributes
Color myLineColor
boolean isPenDown
double myStrokeWidth
List< Color > myCustom
double[] myLineProperty
Static Private Attributes
static final long serialVersionUID = -1512292990210270763L
static final int DASHED_STROKE_WIDTH = 5
static final double SOLID_STROKE_WIDTH_1 = .1
static final double SOLID_STROKE_WIDTH_0 = .1
static final int DOTTED_STROKE_WIDTH_1 = 3
static final double DOTTED_STROKE_WIDTH_0 = .2
static final int DEFAULT_LINE_PROPERTY = 1
static final int STROKE_DASH_OFFSET_VALUE = 50
static final double DEFAULT_STROKE_WIDTH =3
Detailed Description
Set the properties of Pen.
Author
Kevin Li
Definition at line 13 of file Pen.java.
Constructor & Destructor Documentation
model.Pen.Pen ()
Set the default property of the pen.
Definition at line 33 of file Pen.java.
References model.Pen.DEFAULT_LINE_PROPERTY, and model.Pen.DEFAULT_STROKE_WIDTH.
Member Function Documentation
void model.Pen.changeLineProperty (String properties)
Change the properties of the line.
Parameters
properties name of the properties of the line
Definition at line 145 of file Pen.java.
References model.Pen.DASHED_STROKE_WIDTH, model.Pen.DOTTED_STROKE_WIDTH_0, model.Pen.DOTTED_STROKE_WIDTH_1, model.Pen.setPenDown(), model.Pen.SOLID_STROKE_WIDTH_0, and model.Pen.SOLID_STROKE_WIDTH_1.
Referenced by view.SettingsView.addLineProperty().
void model.Pen.clear ()
Clear the Customized color and set the pen color to default white.
Definition at line 136 of file Pen.java.
References model.Pen.setPenColor().
Referenced by model.SlogoModel.clear().
Line model.Pen.createLine (double[] start, double[] end, Color color)
Help method of drawLine.
Parameters
start starting point of the line
end ending point of the line
color color of the line
Returns
the line
Definition at line 116 of file Pen.java.
Referenced by model.Pen.drawLine().
Line model.Pen.drawLine (double[] start, double[] end)
Get the starting and ending point and draw the line.
Parameters
start starting point of the line
end ending point of the line
Returns
the line
Definition at line 99 of file Pen.java.
References model.Pen.createLine().
Referenced by model.Turtle.moveTurtleAndDrawLine().
List<Color> model.Pen.getCustom ()
Get the list of customized color.
Returns
customized color list
Definition at line 129 of file Pen.java.
References model.Pen.myCustom.
Referenced by instructions.commands.GetPenColor.execute(), instructions.commands.SetPenColor.execute(), and instructions.commands.SetPalette.execute().
Color model.Pen.getPenColor ()
Get the pen color.
Returns
the color of the pen
Definition at line 89 of file Pen.java.
References model.Pen.myLineColor.
Referenced by instructions.commands.GetPenColor.execute().
double model.Pen.isPenDown ()
Return if the pen is down. Return 0 when up, 1 when down.
Returns
Definition at line 78 of file Pen.java.
void model.Pen.setCustom (List< Color > custom)
Set the Customized color list.
Parameters
custom customized color list
Definition at line 46 of file Pen.java.
Referenced by model.Turtle.setPenCustom().
void model.Pen.setPenColor (Color color)
Set the pen color.
Parameters
color color of the pen
Definition at line 62 of file Pen.java.
Referenced by model.Turtle.changePenColor(), model.Pen.clear(), and instructions.commands.SetPenColor.execute().
void model.Pen.setPenDown (boolean state)
Set the pen down.
Parameters
state state to represent if the pen is up or down
Definition at line 70 of file Pen.java.
Referenced by view.SettingsView.addLineProperty(), model.Pen.changeLineProperty(), instructions.commands.PenUp.execute(), and instructions.commands.PenDown.execute().
void model.Pen.setStrokeWidth (double width)
Set the stroke width of the pen.
Parameters
width width of the stroke
Definition at line 54 of file Pen.java.
Referenced by instructions.commands.SetPenSize.execute(), and model.SlogoModel.setPenSize().
Member Data Documentation
final int model.Pen.DASHED_STROKE_WIDTH = 5 static private
Definition at line 16 of file Pen.java.
Referenced by model.Pen.changeLineProperty().
final int model.Pen.DEFAULT_LINE_PROPERTY = 1 static private
Definition at line 21 of file Pen.java.
Referenced by model.Pen.Pen().
final double model.Pen.DEFAULT_STROKE_WIDTH =3 static private
Definition at line 23 of file Pen.java.
Referenced by model.Pen.Pen().
final double model.Pen.DOTTED_STROKE_WIDTH_0 = .2 static private
Definition at line 20 of file Pen.java.
Referenced by model.Pen.changeLineProperty().
final int model.Pen.DOTTED_STROKE_WIDTH_1 = 3 static private
Definition at line 19 of file Pen.java.
Referenced by model.Pen.changeLineProperty().
boolean model.Pen.isPenDown private
Definition at line 25 of file Pen.java.
Referenced by instructions.commands.IsPenDown.execute().
List<Color> model.Pen.myCustom private
Definition at line 27 of file Pen.java.
Referenced by model.Pen.getCustom().
Color model.Pen.myLineColor private
Definition at line 24 of file Pen.java.
Referenced by model.Pen.getPenColor().
double [] model.Pen.myLineProperty private
Definition at line 28 of file Pen.java.
double model.Pen.myStrokeWidth private
Definition at line 26 of file Pen.java.
final long model.Pen.serialVersionUID = -1512292990210270763L static private
Definition at line 14 of file Pen.java.
final double model.Pen.SOLID_STROKE_WIDTH_0 = .1 static private
Definition at line 18 of file Pen.java.
Referenced by model.Pen.changeLineProperty().
final double model.Pen.SOLID_STROKE_WIDTH_1 = .1 static private
Definition at line 17 of file Pen.java.
Referenced by model.Pen.changeLineProperty().
final int model.Pen.STROKE_DASH_OFFSET_VALUE = 50 static private
Definition at line 22 of file Pen.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/model/Pen.java