slogo_team02: model.VariablesList Class Reference
model.VariablesList Class Reference
Public Member Functions
VariablesList ()
void add (String variableName, double value)
void addScope ()
void remove (Object variableName) throws InvalidArgumentsException
void removeScope ()
double get (String variableName) throws InvalidArgumentsException
List< String > generate ()
void clear ()
Private Attributes
Map< String, Double > myVariables
Stack< Map< String, Double > > myScope
Static Private Attributes
static final long serialVersionUID = 3790539722809452079L
Detailed Description
VariablesList class. Maps variables to values and error checks for those variables. This class is to be accessed by the commands.
Author
slogo_team02 a.k.a. TEAM ROCKET a.k.a. Mengen Huang, Kevin Li, Jennie Ju, Sandy Lee
Definition at line 21 of file VariablesList.java.
Constructor & Destructor Documentation
model.VariablesList.VariablesList ()
Instantiate the variable list.
Definition at line 30 of file VariablesList.java.
Member Function Documentation
void model.VariablesList.add (String variableName, double value)
Add variable name and value into variable list.
Parameters
variableName name of the variable
value value of the variable
Definition at line 40 of file VariablesList.java.
Referenced by instructions.commands.DoTimes.execute(), instructions.commands.MakeVariable.execute(), and instructions.commands.For.execute().
void model.VariablesList.addScope ()
Add in scope.
Definition at line 47 of file VariablesList.java.
References model.VariablesList.myVariables.
Referenced by instructions.UserDefinedCommand.execute().
void model.VariablesList.clear ()
Clears list of variables.
Implements model.Feature.
Definition at line 113 of file VariablesList.java.
List<String> model.VariablesList.generate ()
Generate the list of the variable name and value. to pass to the front-end view package.
Returns
list of the string representing variable name and value
Definition at line 98 of file VariablesList.java.
Referenced by view.VariablesView.update().
double model.VariablesList.get (String variableName) throws InvalidArgumentsException
Get the variable according to the name of the variable.
Parameters
variableName the name of the variable
Returns
Return the value of the variable
Exceptions
InvalidArgumentsException throw the exception when the variable name does not exist
Definition at line 84 of file VariablesList.java.
Referenced by instructions.commands.DoTimes.execute(), instructions.commands.MakeVariable.execute(), instructions.commands.For.execute(), instructions.VariableInstruction.execute(), and instructions.UserDefinedCommand.execute().
void model.VariablesList.remove (Object variableName) throws InvalidArgumentsException
Remove the variable from the list.
Implements model.Feature.
Definition at line 56 of file VariablesList.java.
void model.VariablesList.removeScope ()
Remove the variable from the scope.
Definition at line 73 of file VariablesList.java.
Referenced by instructions.UserDefinedCommand.execute().
Member Data Documentation
Stack<Map<String, Double> > model.VariablesList.myScope private
Definition at line 23 of file VariablesList.java.
Map<String, Double> model.VariablesList.myVariables private
Definition at line 22 of file VariablesList.java.
Referenced by model.VariablesList.addScope().
final long model.VariablesList.serialVersionUID = 3790539722809452079L static private
Definition at line 25 of file VariablesList.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/model/VariablesList.java