slogo_team02: view.SlogoWindow Class Reference
view.SlogoWindow Class Reference
Public Member Functions
SlogoWindow (Locale locale, double width, double height) throws InvalidArgumentsException
void update (Observable o, Object arg)
SlogoModel getModel ()
void loadFile (History history)
Package Attributes
KeyControls myControls
TurtleView myTurtleView
InputView myInputView
DataView myDataView
HistoryResultsView myHistoryResultsView
SettingsView mySettingsView
SlogoModel myModel
ObservableData myOD
Private Member Functions
void onClickCommand ()
double[] handleClickInstr (MouseEvent mouseEvent, Instruction current)
Static Private Attributes
static final long serialVersionUID = 4532547099439124045L
static final double DEFAULT_XCOORDINATE = 300
static final double DEFAULT_YCOORDINATE = 150
Detailed Description
The Slogo window where all the view elements are instantiated. Bridge the front-end GUI and back-end model as the Observer.
Author
Mengen Huang
Kevin Li
Definition at line 30 of file SlogoWindow.java.
Constructor & Destructor Documentation
view.SlogoWindow.SlogoWindow (Locale locale, double width, double height) throws InvalidArgumentsException
Instantiate the SlogoWindow.
Parameters
locale the language and locale used in the window
width width of View
height height of View
Definition at line 51 of file SlogoWindow.java.
References model.SlogoModel.load(), and view.SlogoWindow.onClickCommand().
Member Function Documentation
SlogoModel view.SlogoWindow.getModel ()
Get the model of the window.
Returns
the model corresponding to the window
Definition at line 105 of file SlogoWindow.java.
References view.SlogoWindow.myModel.
double [] view.SlogoWindow.handleClickInstr (MouseEvent mouseEvent, Instruction current) private
Help function of onClickCommand to handle Click Instruction.
Parameters
mouseEvent
current current Instruction
Returns
the coordinates where the mouseEvent takes place
Definition at line 187 of file SlogoWindow.java.
References instructions.Instruction.addParam().
void view.SlogoWindow.loadFile (History history)
Load the file which stores the history commands.
Parameters
history The history commands recorded
Definition at line 113 of file SlogoWindow.java.
References model.SlogoModel.getMyData(), and model.ObservableData.loadFile().
void view.SlogoWindow.onClickCommand () private
Click on or move the turtle to change the state(image) if the command is listed.
Definition at line 122 of file SlogoWindow.java.
References model.ObservableData.get(), and model.SlogoModel.getMyData().
Referenced by view.SlogoWindow.SlogoWindow().
void view.SlogoWindow.update (Observable o, Object arg)
Override method by Observer Pattern. Update all view when Observable data change and notify the observers.
Definition at line 84 of file SlogoWindow.java.
References view.SettingsView.changeBGPicked(), view.TurtleView.changeColor(), view.SettingsView.changePenPicked(), view.DataView.update(), view.HistoryResultsView.update(), and view.TurtleView.update().
Member Data Documentation
final double view.SlogoWindow.DEFAULT_XCOORDINATE = 300 static private
Definition at line 42 of file SlogoWindow.java.
final double view.SlogoWindow.DEFAULT_YCOORDINATE = 150 static private
Definition at line 43 of file SlogoWindow.java.
KeyControls view.SlogoWindow.myControls package
Definition at line 34 of file SlogoWindow.java.
DataView view.SlogoWindow.myDataView package
Definition at line 37 of file SlogoWindow.java.
HistoryResultsView view.SlogoWindow.myHistoryResultsView package
Definition at line 38 of file SlogoWindow.java.
InputView view.SlogoWindow.myInputView package
Definition at line 36 of file SlogoWindow.java.
SlogoModel view.SlogoWindow.myModel package
Definition at line 40 of file SlogoWindow.java.
Referenced by view.SlogoWindow.getModel().
ObservableData view.SlogoWindow.myOD package
Definition at line 41 of file SlogoWindow.java.
SettingsView view.SlogoWindow.mySettingsView package
Definition at line 39 of file SlogoWindow.java.
TurtleView view.SlogoWindow.myTurtleView package
Definition at line 35 of file SlogoWindow.java.
final long view.SlogoWindow.serialVersionUID = 4532547099439124045L static private
Definition at line 33 of file SlogoWindow.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/SlogoWindow.java