slogo_team02: model.SlogoModel Class Reference
model.SlogoModel Class Reference
Public Member Functions
SlogoModel (Locale locale)
void parseAndExecute (String s) throws InvalidArgumentsException
boolean executeCommands (Stack< Instruction > commandStack) throws InvalidArgumentsException
void load ()
void toggleTurtle ()
void clear ()
void showToHistoryView (String text)
void accessHelpHTML ()
ObservableData getMyData ()
Parser getParser ()
Locale getLocale ()
void initializeBGColor (ObservableList< Color > customColors)
void initializePenColor (ObservableList< Color > customColors)
void rerun () throws InvalidArgumentsException
void setPenSize (double width)
Package Attributes
Parser myParser
Private Member Functions
void showOnView (double returnValue)
Private Attributes
ObservableData myData
Locale myLocale
Static Private Attributes
static final long serialVersionUID = -7452943156645209670L
static final String HELP_URL = "http://www.cs.duke.edu/courses/compsci308/current/assign/03_slogo/commands.php"
Detailed Description
The model class of the program. The Observable class that notifies the observer when elements get changed.
Author
Kevin Li
Mengen Huang
Definition at line 22 of file SlogoModel.java.
Constructor & Destructor Documentation
model.SlogoModel.SlogoModel (Locale locale)
Create the model.
Parameters
locale the language and locale the model uses
Definition at line 34 of file SlogoModel.java.
Member Function Documentation
void model.SlogoModel.accessHelpHTML ()
Access the Help HTML page.
Definition at line 123 of file SlogoModel.java.
Referenced by view.SettingsView.addButtons().
void model.SlogoModel.clear ()
Clear the data in Observable Data.
Definition at line 104 of file SlogoModel.java.
References model.ObservableData.clear(), model.Pen.clear(), model.Turtle.getPen(), model.ObservableData.getTurtle(), and model.SlogoModel.load().
Referenced by view.SettingsView.addButtons().
boolean model.SlogoModel.executeCommands (Stack< Instruction > commandStack) throws InvalidArgumentsException
Execute the command in the commandStack.
Parameters
commandStack The stack where stores all the commands to be processed
Returns
If the stack is empty
Exceptions
InvalidArgumentsException throw the exception when the command in invalid
Definition at line 60 of file SlogoModel.java.
References instructions.Instruction.execute(), model.ObservableData.get(), and model.SlogoModel.showOnView().
Referenced by model.SlogoModel.parseAndExecute().
Locale model.SlogoModel.getLocale ()
Get the locale of the model.
Returns
the locale of the model
Definition at line 153 of file SlogoModel.java.
References model.SlogoModel.myLocale.
ObservableData model.SlogoModel.getMyData ()
Get the observable data.
Returns
the observable data
Definition at line 137 of file SlogoModel.java.
References model.SlogoModel.myData.
Referenced by view.SettingsView.addBGColorPicker(), view.SettingsView.addLineProperty(), view.SettingsView.addPenColorPicker(), view.SettingsView.addTurtleChoices(), view.SlogoWindow.loadFile(), view.KeyControls.makeKeyCommands(), and view.SlogoWindow.onClickCommand().
Parser model.SlogoModel.getParser ()
Get the parser of the model.
Returns
the parser of the model
Definition at line 145 of file SlogoModel.java.
References model.SlogoModel.myParser.
Referenced by view.KeyControls.setKeyMap().
void model.SlogoModel.initializeBGColor (ObservableList< Color > customColors)
Initialize the background color.
Parameters
customColors The list of custom colors
Definition at line 161 of file SlogoModel.java.
References model.ObservableData.get().
Referenced by view.SettingsView.addBGColorPicker().
void model.SlogoModel.initializePenColor (ObservableList< Color > customColors)
Initialize the pen color.
Parameters
customColors list of customized colo
Definition at line 171 of file SlogoModel.java.
References model.ObservableData.getTurtle(), and model.Turtle.setPenCustom().
Referenced by view.SettingsView.addPenColorPicker().
void model.SlogoModel.load ()
Notify the observers about the change and passed in the observable data.
Definition at line 88 of file SlogoModel.java.
Referenced by model.SlogoModel.clear(), model.SlogoModel.rerun(), model.SlogoModel.showOnView(), model.SlogoModel.showToHistoryView(), view.SlogoWindow.SlogoWindow(), and model.SlogoModel.toggleTurtle().
void model.SlogoModel.parseAndExecute (String s) throws InvalidArgumentsException
Parse and execute the input passed from the front-end view package.
Parameters
s Command user typed in and passed from view
Exceptions
InvalidArgumentsException throw the exception when the command is invalid
Definition at line 46 of file SlogoModel.java.
References model.SlogoModel.executeCommands(), parser.Parser.parse(), and model.SlogoModel.showToHistoryView().
Referenced by view.InputView.initSubmitButton(), and view.KeyControls.makeKeyCommands().
void model.SlogoModel.rerun () throws InvalidArgumentsException
Get the saved history commands and rerun all the commands.
Exceptions
InvalidArgumentsException Throw the exception when the commands is invalid
Definition at line 181 of file SlogoModel.java.
References model.ObservableData.get(), and model.SlogoModel.load().
void model.SlogoModel.setPenSize (double width)
Set the size of the pen stroke.
Parameters
width width of the pen stroke
Definition at line 193 of file SlogoModel.java.
References model.Turtle.getPen(), model.ObservableData.getTurtle(), and model.Pen.setStrokeWidth().
Referenced by view.SettingsView.addPenSlider().
void model.SlogoModel.showOnView (double returnValue) private
Show the command return value on view.
Parameters
returnValue command return value
Definition at line 79 of file SlogoModel.java.
References model.ObservableData.changeReturn(), and model.SlogoModel.load().
Referenced by model.SlogoModel.executeCommands().
void model.SlogoModel.showToHistoryView (String text)
Display the string to the History view.
Parameters
text The text to show in history view
Definition at line 114 of file SlogoModel.java.
References model.ObservableData.get(), and model.SlogoModel.load().
Referenced by model.SlogoModel.parseAndExecute().
void model.SlogoModel.toggleTurtle ()
Set the reference grid visible.
Definition at line 96 of file SlogoModel.java.
References model.ObservableData.getTurtle(), model.SlogoModel.load(), and model.Turtle.toggleVisible().
Referenced by view.SettingsView.addButtons().
Member Data Documentation
final String model.SlogoModel.HELP_URL = "http://www.cs.duke.edu/courses/compsci308/current/assign/03_slogo/commands.php" static private
Definition at line 25 of file SlogoModel.java.
ObservableData model.SlogoModel.myData private
Definition at line 26 of file SlogoModel.java.
Referenced by model.SlogoModel.getMyData().
Locale model.SlogoModel.myLocale private
Definition at line 27 of file SlogoModel.java.
Referenced by model.SlogoModel.getLocale().
Parser model.SlogoModel.myParser package
Definition at line 28 of file SlogoModel.java.
Referenced by model.SlogoModel.getParser().
final long model.SlogoModel.serialVersionUID = -7452943156645209670L static private
Definition at line 24 of file SlogoModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/model/SlogoModel.java