slogo_team02: view.SettingsView Class Reference
view.SettingsView Class Reference
Public Member Functions
SettingsView (SlogoModel model, TurtleView view, double width, double height, Locale locale)
void changeBGPicked (Color generate)
void changePenPicked (Color generate)
Static Public Attributes
static final String DEFAULT_DISPLAY_RESOURCE = "resources.languages/Display"
Static Protected Attributes
static final String IMAGE_1 = "image_1.gif"
static final String IMAGE_2 = "image_2.gif"
Package Attributes
ColorPicker myBGColor
ColorPicker myPenColor
Slider myPenSize
ComboBox< String > myLineProperties
ComboBox< Image > myTurtleChoices
SlogoModel myModel
Locale myLocale
ResourceBundle languageBundle
Private Member Functions
void setView (double width, double height)
void addBGColorPicker (TurtleView view)
void addPenColorPicker ()
void addLineProperty ()
void addPenSlider ()
void addTurtleChoices ()
void addTurtleUpload ()
void addButtons (SlogoModel model, TurtleView view)
Button makeButton (String property, EventHandler< ActionEvent > handler)
ObservableList< Color > getCustomColors (ColorPicker colorpicker)
Static Private Attributes
static final long serialVersionUID = 660774956006597491L
Detailed Description
The settings view at the top of the window
Author
Kevin Li
Mengen Huang
Definition at line 45 of file SettingsView.java.
Constructor & Destructor Documentation
view.SettingsView.SettingsView (SlogoModel model, TurtleView view, double width, double height, Locale locale)
Create the SettingsView
Parameters
model model used in the window
view turtle View passed in
width width of the view
height height of the view
locale current language and locale applied
Definition at line 69 of file SettingsView.java.
References view.SettingsView.addBGColorPicker(), view.SettingsView.addButtons(), view.SettingsView.addLineProperty(), view.SettingsView.addPenColorPicker(), view.SettingsView.addPenSlider(), view.SettingsView.addTurtleChoices(), view.SettingsView.addTurtleUpload(), and view.SettingsView.setView().
Member Function Documentation
void view.SettingsView.addBGColorPicker (TurtleView view) private
Add new color of TurtleView background color
Parameters
view turtleView
Definition at line 99 of file SettingsView.java.
References view.TurtleView.changeColor(), model.ObservableData.get(), view.SettingsView.getCustomColors(), model.SlogoModel.getMyData(), and model.SlogoModel.initializeBGColor().
Referenced by view.SettingsView.SettingsView().
void view.SettingsView.addButtons (SlogoModel model, TurtleView view) private
method to add buttons
Parameters
model SlogoModel
view TurtleView
Definition at line 286 of file SettingsView.java.
References model.SlogoModel.accessHelpHTML(), model.SlogoModel.clear(), view.SettingsView.makeButton(), view.TurtleView.toggleGrid(), and model.SlogoModel.toggleTurtle().
Referenced by view.SettingsView.SettingsView().
void view.SettingsView.addLineProperty () private
Enable the user to specify the properties of the line
Definition at line 140 of file SettingsView.java.
References model.Pen.changeLineProperty(), model.SlogoModel.getMyData(), model.Turtle.getPen(), model.ObservableData.getTurtle(), and model.Pen.setPenDown().
Referenced by view.SettingsView.SettingsView().
void view.SettingsView.addPenColorPicker () private
Enable the user to pick the pen color
Definition at line 120 of file SettingsView.java.
References model.Turtle.changePenColor(), view.SettingsView.getCustomColors(), model.SlogoModel.getMyData(), model.ObservableData.getTurtle(), and model.SlogoModel.initializePenColor().
Referenced by view.SettingsView.SettingsView().
void view.SettingsView.addPenSlider () private
add slider to specify the pen properties
Definition at line 177 of file SettingsView.java.
References model.SlogoModel.setPenSize().
Referenced by view.SettingsView.SettingsView().
void view.SettingsView.addTurtleChoices () private
More choices of turtle image
Definition at line 205 of file SettingsView.java.
References model.SlogoModel.getMyData(), model.ObservableData.getTurtle(), model.Turtle.initListofTurtles(), and model.Turtle.setShape().
Referenced by view.SettingsView.SettingsView().
void view.SettingsView.addTurtleUpload () private
Enable the user to upload self-defined turtle image
Definition at line 255 of file SettingsView.java.
Referenced by view.SettingsView.SettingsView().
void view.SettingsView.changeBGPicked (Color generate)
change the background color of turtle view after user picks
Parameters
generate Color the user picks
Definition at line 326 of file SettingsView.java.
Referenced by view.SlogoWindow.update().
void view.SettingsView.changePenPicked (Color generate)
change the pen color after user picks
Parameters
generate Color the user picks
Definition at line 335 of file SettingsView.java.
Referenced by view.SlogoWindow.update().
ObservableList<Color> view.SettingsView.getCustomColors (ColorPicker colorpicker) private
get the Color the user picks
Parameters
colorpicker ColorPicker list of Color
Definition at line 317 of file SettingsView.java.
Referenced by view.SettingsView.addBGColorPicker(), and view.SettingsView.addPenColorPicker().
Button view.SettingsView.makeButton (String property, EventHandler< ActionEvent > handler) private
Method to make buttons
Parameters
property String to show on the button
handler the EventHandler which executed after the ActionEvent is triggered
Returns
the button made
Definition at line 305 of file SettingsView.java.
Referenced by view.SettingsView.addButtons().
void view.SettingsView.setView (double width, double height) private
set the size of the view
Parameters
width width of the view
height height of the view
Definition at line 91 of file SettingsView.java.
Referenced by view.SettingsView.SettingsView().
Member Data Documentation
final String view.SettingsView.DEFAULT_DISPLAY_RESOURCE = "resources.languages/Display" static
Definition at line 48 of file SettingsView.java.
final String view.SettingsView.IMAGE_1 = "image_1.gif" static protected
Definition at line 55 of file SettingsView.java.
final String view.SettingsView.IMAGE_2 = "image_2.gif" static protected
Definition at line 56 of file SettingsView.java.
ResourceBundle view.SettingsView.languageBundle package
Definition at line 59 of file SettingsView.java.
ColorPicker view.SettingsView.myBGColor package
Definition at line 49 of file SettingsView.java.
ComboBox<String> view.SettingsView.myLineProperties package
Definition at line 52 of file SettingsView.java.
Locale view.SettingsView.myLocale package
Definition at line 58 of file SettingsView.java.
SlogoModel view.SettingsView.myModel package
Definition at line 54 of file SettingsView.java.
ColorPicker view.SettingsView.myPenColor package
Definition at line 50 of file SettingsView.java.
Slider view.SettingsView.myPenSize package
Definition at line 51 of file SettingsView.java.
ComboBox<Image> view.SettingsView.myTurtleChoices package
Definition at line 53 of file SettingsView.java.
final long view.SettingsView.serialVersionUID = 660774956006597491L static private
Definition at line 47 of file SettingsView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/SettingsView.java