slogo_team02: instructions.Instruction Interface Reference
instructions.Instruction Interface Reference
Public Member Functions
double execute (ObservableData data) throws InvalidArgumentsException
int getNumParams ()
void addParam (Instruction param)
Detailed Description
Highest superclass for the parsing tree tree that will be made to represent an expression.
Author
Jennie Ju, Sandy Lee
Definition at line 16 of file Instruction.java.
Member Function Documentation
void instructions.Instruction.addParam (Instruction param)
Adds an instruction to the list of parameters for the instruction
Parameters
param Instruction used as a parameter in the instruction
Implemented in instructions.ParameterInstruction, instructions.commands.ShowTurtle, and instructions.ZeroParamInstruction.
Referenced by view.SlogoWindow.handleClickInstr().
double instructions.Instruction.execute (ObservableData data) throws InvalidArgumentsException
Executes the functionality of the instruction to change data in the program, such as lists of history and scene nodes during drawing.
Returns
Double value of the expression
Parameters
data of observables
Exceptions
InvalidArgumentsException throws when there is an argument error.
Implemented in instructions.UserDefinedCommand, instructions.ListInstruction, instructions.commands.MakeUserInstruction, instructions.commands.SetPalette, instructions.VariableInstruction, instructions.commands.For, instructions.ConstantInstruction, instructions.commands.IfElse, instructions.commands.Ask, instructions.commands.DoTimes, instructions.commands.MakeVariable, instructions.commands.Tell, instructions.commands.Backward, instructions.commands.GetShape, instructions.commands.SetPenColor, instructions.commands.Equal, instructions.commands.GetPenColor, instructions.commands.IsShowing, instructions.commands.Left, instructions.commands.SetBackground, instructions.commands.SetPosition, instructions.commands.SetShape, instructions.commands.And, instructions.commands.Difference, instructions.commands.Forward, instructions.commands.NotEqual, instructions.commands.Or, instructions.commands.Random, instructions.commands.Right, instructions.commands.SetTowards, instructions.commands.Sum, instructions.commands.ClearScreen, instructions.commands.GreaterThan, instructions.commands.Heading, instructions.commands.Home, instructions.commands.LessThan, instructions.commands.Minus, instructions.commands.NaturalLog, instructions.commands.NumTurtles, instructions.commands.PenDown, instructions.commands.Remainder, instructions.commands.SetHeading, instructions.commands.SetPenSize, instructions.commands.ShowTurtle, instructions.commands.ArcTangent, instructions.commands.ClearStamps, instructions.commands.Cosine, instructions.commands.ID, instructions.commands.If, instructions.commands.IsPenDown, instructions.commands.PenUp, instructions.commands.Product, instructions.commands.Sine, instructions.commands.XCoordinate, instructions.commands.YCoordinate, instructions.commands.Not, instructions.commands.Power, instructions.commands.Quotient, instructions.commands.Stamp, instructions.commands.HideTurtle, instructions.commands.PiConstant, instructions.commands.Tangent, and instructions.commands.Repeat.
Referenced by instructions.commands.Sum.execute(), instructions.commands.Backward.execute(), instructions.commands.MakeVariable.execute(), instructions.UserDefinedCommand.execute(), and model.SlogoModel.executeCommands().
int instructions.Instruction.getNumParams ()
Gets the number of parameters used in the instruction, Used in the parser when evaluating different types of instructions with various numbers of parameters
Returns
int number of parameters
Implemented in instructions.ParameterInstruction, instructions.commands.ShowTurtle, and instructions.ZeroParamInstruction.
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/instructions/Instruction.java