slogo_team02: model.ObservableData Class Reference
model.ObservableData Class Reference
Public Member Functions
ObservableData (Locale locale)
Turtle getTurtle ()
TurtlesList getTurtles ()
Feature get (String classKey)
void clear ()
void loadFile (History history)
void changeReturn (double returnValue)
String getReturn ()
Private Member Functions
void addAllToMyFeatures (Feature...features)
Private Attributes
Map< String, Feature > myFeatures
Turtle myTurtle
Locale myLocale
String myReturn
TurtlesList myTurtles
Static Private Attributes
static final long serialVersionUID = -8636982923572910062L
Detailed Description
All the data that can be observed by the front-end view package.
Author
Jennie Ju
Kevin Li
Definition at line 13 of file ObservableData.java.
Constructor & Destructor Documentation
model.ObservableData.ObservableData (Locale locale)
Create the ObservableData class.
Parameters
locale language and locale the current model uses
Definition at line 28 of file ObservableData.java.
References model.ObservableData.addAllToMyFeatures().
Member Function Documentation
void model.ObservableData.addAllToMyFeatures (Feature... features) private
Add all the observable class in model package to the feature map.
Parameters
features features to add into the feature map
Definition at line 47 of file ObservableData.java.
Referenced by model.ObservableData.ObservableData().
void model.ObservableData.changeReturn (double returnValue)
Update the content of Return Value View.
Parameters
returnValue the updated command return value
Definition at line 105 of file ObservableData.java.
Referenced by model.SlogoModel.showOnView().
void model.ObservableData.clear ()
Clear the feature map.
Definition at line 83 of file ObservableData.java.
References model.Turtle.clear().
Referenced by model.SlogoModel.clear().
Feature model.ObservableData.get (String classKey)
Definition at line 72 of file ObservableData.java.
Referenced by view.SettingsView.addBGColorPicker(), instructions.commands.IsShowing.execute(), model.SlogoModel.executeCommands(), model.SlogoModel.initializeBGColor(), parser.InstructionFactory.makeInstruction(), view.KeyControls.makeKeyCommands(), view.SlogoWindow.onClickCommand(), model.SlogoModel.rerun(), and model.SlogoModel.showToHistoryView().
String model.ObservableData.getReturn ()
Get the updated command return value.
Returns
updated command return value
Definition at line 114 of file ObservableData.java.
References model.ObservableData.myReturn.
Turtle model.ObservableData.getTurtle ()
Get the Turtle class in model package.
Returns
Turtle class
Definition at line 59 of file ObservableData.java.
References model.ObservableData.myTurtle.
Referenced by view.SettingsView.addLineProperty(), view.SettingsView.addPenColorPicker(), view.SettingsView.addTurtleChoices(), model.SlogoModel.clear(), instructions.commands.Stamp.execute(), instructions.commands.IsPenDown.execute(), instructions.commands.ClearStamps.execute(), instructions.commands.XCoordinate.execute(), instructions.commands.YCoordinate.execute(), instructions.commands.PenUp.execute(), instructions.commands.Heading.execute(), instructions.commands.ShowTurtle.execute(), instructions.commands.PenDown.execute(), instructions.commands.Home.execute(), model.SlogoModel.initializePenColor(), model.SlogoModel.setPenSize(), and model.SlogoModel.toggleTurtle().
TurtlesList model.ObservableData.getTurtles ()
Gets the TurtlesList for all turtles in the current program.
Returns
TurtlesList for the current program
Definition at line 67 of file ObservableData.java.
References model.ObservableData.myTurtles.
Referenced by instructions.commands.ID.execute(), and instructions.commands.NumTurtles.execute().
void model.ObservableData.loadFile (History history)
Load the window by taking in History.
Parameters
history
Definition at line 97 of file ObservableData.java.
Referenced by view.SlogoWindow.loadFile().
Member Data Documentation
Map<String, Feature> model.ObservableData.myFeatures private
Definition at line 15 of file ObservableData.java.
Locale model.ObservableData.myLocale private
Definition at line 18 of file ObservableData.java.
String model.ObservableData.myReturn private
Definition at line 20 of file ObservableData.java.
Referenced by model.ObservableData.getReturn().
Turtle model.ObservableData.myTurtle private
Definition at line 16 of file ObservableData.java.
Referenced by model.ObservableData.getTurtle().
TurtlesList model.ObservableData.myTurtles private
Definition at line 22 of file ObservableData.java.
Referenced by model.ObservableData.getTurtles().
final long model.ObservableData.serialVersionUID = -8636982923572910062L static private
Definition at line 14 of file ObservableData.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/model/ObservableData.java