slogo_team02: parser.Parser Class Reference
parser.Parser Class Reference
Public Member Functions
Parser (ObservableData data)
void setLanguage (ResourceBundle bundle)
Stack< Instruction > parse (String input) throws InvalidArgumentsException
Private Member Functions
Stack< Instruction > parseTokens (List< String > tokens) throws InvalidArgumentsException
boolean isRightBracket (String token)
boolean isLeftBracket (String token)
int findMatchingBracket (List< String > tokens, int openPos)
void addParams (Instruction instr, Stack< Instruction > iStack) throws InvalidArgumentsException
Private Attributes
ResourceBundle myLanguageBundle
Tokenizer myTokenizer
InstructionFactory myIFactory
Static Private Attributes
static final long serialVersionUID = 7476618255022085064L
static final String PARAMETER_ERROR = "NOT ENOUGH PARAMETERS."
Detailed Description
Parser for converting strings of instructions into stacks of executable instructions.
General format for parsing: - Uses two stacks: one for holding double values from instruction returns while parsing the string and one to return all instructions to the model
Author
Jennie Ju, Sandy Lee
Definition at line 28 of file Parser.java.
Constructor & Destructor Documentation
parser.Parser.Parser (ObservableData data)
Constructor for a Parser. Creates a new instance of the Tokenizer.
Parameters
data of observables
Definition at line 39 of file Parser.java.
Member Function Documentation
void parser.Parser.addParams (Instruction instr, Stack< Instruction > iStack) throws InvalidArgumentsException private
For each instruction, checks to see how many inputs are needed for the instruction - Pops from double value stack if inputs are needed -
Parameters
instr instruction to add parameters to
iStack of parameters
Exceptions
InvalidArgumentsException throws when there is not enough parameters
Definition at line 161 of file Parser.java.
Referenced by parser.Parser.parseTokens().
int parser.Parser.findMatchingBracket (List< String > tokens, int openPos) private
Parameters
tokens of strings
openPos position of right bracket
Returns
position of matching left bracket
Definition at line 128 of file Parser.java.
References parser.Parser.isLeftBracket(), and parser.Parser.isRightBracket().
Referenced by parser.Parser.parseTokens().
boolean parser.Parser.isLeftBracket (String token) private
Parameters
token string
Returns
1 if it is a left bracket, 0 otherwise
Definition at line 119 of file Parser.java.
Referenced by parser.Parser.findMatchingBracket().
boolean parser.Parser.isRightBracket (String token) private
Parameters
token string
Returns
1 if it is a right bracket, 0 otherwise
Definition at line 111 of file Parser.java.
Referenced by parser.Parser.findMatchingBracket(), and parser.Parser.parseTokens().
Stack<Instruction> parser.Parser.parse (String input) throws InvalidArgumentsException
Iterates through string tokens in reverse order to create Instruction classes with the InstructionFactory
Parameters
input string input to be parsed
Returns
a stack of instructions to be executed in the Model class
Exceptions
InvalidArgumentsException throws when there is invalid parameter
Definition at line 60 of file Parser.java.
References parser.Parser.parseTokens(), and parser.Tokenizer.tokenize().
Referenced by model.SlogoModel.parseAndExecute(), and view.KeyControls.setKeyMap().
Stack<Instruction> parser.Parser.parseTokens (List< String > tokens) throws InvalidArgumentsException private
Parses token and creates Instruction classes with the InstructionFactory
Parameters
tokens to be parsed and created into instructions
Returns
stack of instructions
Exceptions
InvalidArgumentsException throws when invalid parameters
Definition at line 73 of file Parser.java.
References parser.Parser.addParams(), parser.Parser.findMatchingBracket(), parser.Parser.isRightBracket(), and parser.InstructionFactory.makeInstruction().
Referenced by parser.Parser.parse().
void parser.Parser.setLanguage (ResourceBundle bundle)
sets language bundle
Parameters
bundle of resource
Definition at line 48 of file Parser.java.
Member Data Documentation
InstructionFactory parser.Parser.myIFactory private
Definition at line 33 of file Parser.java.
ResourceBundle parser.Parser.myLanguageBundle private
Definition at line 31 of file Parser.java.
Tokenizer parser.Parser.myTokenizer private
Definition at line 32 of file Parser.java.
final String parser.Parser.PARAMETER_ERROR = "NOT ENOUGH PARAMETERS." static private
Definition at line 30 of file Parser.java.
final long parser.Parser.serialVersionUID = 7476618255022085064L static private
Definition at line 29 of file Parser.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/parser/Parser.java