slogo_team02: model.Turtle Class Reference
model.Turtle Class Reference
Public Member Functions
Turtle ()
void ListofTurtles (ObservableList< Image > shapes)
List< Image > getShapeList ()
void setShape (Image image)
double[] getCoordinates ()
void setCoordinates (double x, double y)
void setVisible (boolean state)
void stampImage ()
void clearStamp ()
double isVisible ()
void rotate (double deltaAngle)
void setAngle (double angle)
double calculateAngle (double currentX, double currentY, double targetX, double targetY)
double getAngle ()
Pen getPen ()
void changePenColor (Color color)
void moveTurtleAndDrawLine (double distance)
double calculateDistance (double[] startCoords, double[] finalCoords)
List< double[]> getCoordList (double x, double y)
Group getDrawing ()
ImageView getTurtleImg ()
Node generate ()
void clear ()
void setPenCustom (ObservableList< Color > customColors)
void toggleVisible ()
void remove (Object n)
void initListofTurtles (ObservableList< Image > items)
Public Member Functions inherited from model.TurtleAbstract
TurtleAbstract ()
Private Member Functions
void initializeTurtle ()
void changeState ()
double[] calculateEndCoord (double distance)
void setTurtleInfo ()
Private Attributes
ImageView myImage
ObservableList< Image > myTurtleShapes
double[] myCoordinates = { DEFAULT_XCOORDINATE, DEFAULT_YCOORDINATE }
double[] myRelativeCoordinates
double myAngle = DEFAULT_TURTLE_ANGLE
Pen myPen
Group myDrawing
Group myLines
Group myStamps
Tooltip myTurtleInfo
Image myDefaultOn
Image myDefaultOff
boolean isVisible
boolean myState = true
Static Private Attributes
static final double _10_0 = 10.0
static final int _10 = 10
static final int FULL_CIRCLE_DEGREE = 360
static final long serialVersionUID = 3491015094836744017L
Additional Inherited Members
Static Protected Attributes inherited from model.TurtleAbstract
static final double DEFAULT_XCOORDINATE = 300
static final double DEFAULT_YCOORDINATE = 150
static final double DEFAULT_REALATIVE_COORDINATE =0
static final double DEFAULT_TURTLE_ANGLE = 0
static final double DEFAULT_TURTLE_SIZE = 30
static final double FULL_ROTATION_DEGREE = 360
static final String DEFAULT_OFF_IMAGE = "default_off.png"
static final String DEFAULT_ON_IMAGE = "default_on.gif"
Detailed Description
Class that simulates the action of the turtle.
Author
Kevin Li
Mengen Huang
Definition at line 22 of file Turtle.java.
Constructor & Destructor Documentation
model.Turtle.Turtle ()
Instantiate all the elements in turtle view.
Definition at line 54 of file Turtle.java.
References model.Turtle.initializeTurtle(), and model.Turtle.setTurtleInfo().
Member Function Documentation
double model.Turtle.calculateAngle (double currentX, double currentY, double targetX, double targetY)
Calculate the angle between two points.
Parameters
currentX current X coordinate
currentY current Y coordinate
targetX target X coordinate
targetY target Y coordinate
Returns
the arc tangent angle between two points
Definition at line 224 of file Turtle.java.
References model.Turtle.FULL_CIRCLE_DEGREE.
Referenced by instructions.commands.SetTowards.execute().
double model.Turtle.calculateDistance (double[] startCoords, double[] finalCoords)
Calculate the distance between two coordinates.
Parameters
startCoords starting coordinates
finalCoords ending coordinates
Returns
the distance between two coordinates
Definition at line 296 of file Turtle.java.
Referenced by instructions.commands.ClearScreen.execute(), instructions.commands.Home.execute(), and instructions.commands.SetPosition.execute().
double [] model.Turtle.calculateEndCoord (double distance) private
Calculate the end coordination after going forward a certain distance.
Parameters
distance the distance the turtle will go forward
Returns
the end coordinate
Definition at line 281 of file Turtle.java.
Referenced by model.Turtle.moveTurtleAndDrawLine().
void model.Turtle.changePenColor (Color color)
Change the pen color.
Parameters
color color the pen color should change to
Definition at line 256 of file Turtle.java.
References model.Pen.setPenColor().
Referenced by view.SettingsView.addPenColorPicker().
void model.Turtle.changeState () private
Change the state of the turtle by setting the turtle with different images.
Definition at line 114 of file Turtle.java.
References model.Turtle.myState.
Referenced by model.Turtle.initializeTurtle().
void model.Turtle.clear ()
Clear the line and stamp. Set the turtle back to the default coordinates and default angle. Update the turtle info.
Implements model.Feature.
Definition at line 360 of file Turtle.java.
References model.TurtleAbstract.DEFAULT_REALATIVE_COORDINATE, model.TurtleAbstract.DEFAULT_TURTLE_ANGLE, model.Turtle.setAngle(), model.Turtle.setCoordinates(), and model.Turtle.setTurtleInfo().
Referenced by model.ObservableData.clear(), and instructions.commands.ClearScreen.execute().
void model.Turtle.clearStamp ()
Clear the stamp turtle images.
Definition at line 180 of file Turtle.java.
Referenced by instructions.commands.ClearStamps.execute().
Node model.Turtle.generate ()
Generate the node to pass to the front end to show.
Returns
The drawing group which contains turtle and lines
Definition at line 350 of file Turtle.java.
References model.Turtle.myDrawing.
double model.Turtle.getAngle ()
Get the angle of the turtle.
Returns
the angle rounded to 0.1
Definition at line 240 of file Turtle.java.
References model.Turtle._10_0.
Referenced by instructions.commands.Heading.execute(), instructions.commands.SetHeading.execute(), instructions.commands.SetTowards.execute(), and model.Turtle.setTurtleInfo().
double [] model.Turtle.getCoordinates ()
Get the Coordinates of the turtle. The center point as (0,0).
Returns
Turtle's relative coordinate to the center of the TurtleView
Definition at line 127 of file Turtle.java.
References model.Turtle.myRelativeCoordinates.
Referenced by instructions.commands.XCoordinate.execute(), instructions.commands.YCoordinate.execute(), and instructions.commands.ClearScreen.execute().
List<double[]> model.Turtle.getCoordList (double x, double y)
Get the Coordinate of all the turtles in one window.
Parameters
x x coordinate
y y coordinate
Returns
list of coordinates
Definition at line 309 of file Turtle.java.
References model.Turtle.setCoordinates().
Referenced by instructions.commands.Home.execute(), and instructions.commands.SetPosition.execute().
Group model.Turtle.getDrawing ()
Get all the elements in drawing.
Returns
Drawing which contains turtle and lines
Definition at line 334 of file Turtle.java.
References model.Turtle.myDrawing.
Referenced by instructions.commands.ShowTurtle.execute().
Pen model.Turtle.getPen ()
Get the pen of the turtle.
Returns
the pen
Definition at line 248 of file Turtle.java.
References model.Turtle.myPen.
Referenced by view.SettingsView.addLineProperty(), model.SlogoModel.clear(), instructions.commands.IsPenDown.execute(), instructions.commands.PenUp.execute(), instructions.commands.PenDown.execute(), and model.SlogoModel.setPenSize().
List<Image> model.Turtle.getShapeList ()
Get the list of shapes of turtles.
Returns
Definition at line 99 of file Turtle.java.
References model.Turtle.myTurtleShapes.
Referenced by instructions.commands.SetShape.execute(), and instructions.commands.GetShape.execute().
ImageView model.Turtle.getTurtleImg ()
Get the turtle image.
Returns
the image of the turtle
Definition at line 342 of file Turtle.java.
References model.Turtle.myImage.
Referenced by instructions.commands.ShowTurtle.execute(), and instructions.commands.GetShape.execute().
void model.Turtle.initializeTurtle () private
Initialize the turtle.
Definition at line 71 of file Turtle.java.
References model.Turtle.changeState(), model.TurtleAbstract.DEFAULT_REALATIVE_COORDINATE, model.TurtleAbstract.DEFAULT_TURTLE_ANGLE, model.TurtleAbstract.DEFAULT_TURTLE_SIZE, model.Turtle.setAngle(), and model.Turtle.setCoordinates().
Referenced by model.Turtle.Turtle().
void model.Turtle.initListofTurtles (ObservableList< Image > items)
Initiate list of turtles.
Parameters
items all the image of the turtles
Definition at line 396 of file Turtle.java.
Referenced by view.SettingsView.addTurtleChoices().
double model.Turtle.isVisible ()
Return value if the turtle is visible.
Returns
1 if visible; 0 if not
Definition at line 189 of file Turtle.java.
void model.Turtle.ListofTurtles (ObservableList< Image > shapes)
Initiate the list of turtles.
Parameters
shapes
Definition at line 91 of file Turtle.java.
void model.Turtle.moveTurtleAndDrawLine (double distance)
Move the turtle and draw the line from the current location.
Parameters
distance the turtle should move forward
Definition at line 264 of file Turtle.java.
References model.Turtle.calculateEndCoord(), model.TurtleAbstract.DEFAULT_XCOORDINATE, model.TurtleAbstract.DEFAULT_YCOORDINATE, model.Pen.drawLine(), model.Turtle.setCoordinates(), and model.Turtle.setTurtleInfo().
Referenced by instructions.commands.Forward.execute(), and instructions.commands.Backward.execute().
void model.Turtle.remove (Object o)
Shared method that remove a specific object from the model.
Parameters
o the object to be removed
Exceptions
InvalidArgumentsException
Implements model.Feature.
Definition at line 388 of file Turtle.java.
void model.Turtle.rotate (double deltaAngle)
Rotate the turtle image according to the given angle.
Parameters
deltaAngle The angle the turtle should rotate
Definition at line 197 of file Turtle.java.
References model.TurtleAbstract.FULL_ROTATION_DEGREE, and model.Turtle.setTurtleInfo().
Referenced by instructions.commands.Right.execute(), and instructions.commands.Left.execute().
void model.Turtle.setAngle (double angle)
Set the angle of rotation.
Parameters
angle angle the image should rotate
Definition at line 209 of file Turtle.java.
References model.TurtleAbstract.FULL_ROTATION_DEGREE.
Referenced by model.Turtle.clear(), instructions.commands.SetHeading.execute(), instructions.commands.SetTowards.execute(), and model.Turtle.initializeTurtle().
void model.Turtle.setCoordinates (double x, double y)
Set the turtle to a specific position.
Parameters
x relative x coordinate
y relative y coordinate
Definition at line 137 of file Turtle.java.
References model.TurtleAbstract.DEFAULT_XCOORDINATE, model.TurtleAbstract.DEFAULT_YCOORDINATE, and model.Turtle.setTurtleInfo().
Referenced by model.Turtle.clear(), model.Turtle.getCoordList(), model.Turtle.initializeTurtle(), and model.Turtle.moveTurtleAndDrawLine().
void model.Turtle.setPenCustom (ObservableList< Color > customColors)
Set the pen color as a customized one.
Parameters
customColors list of customized color
Definition at line 374 of file Turtle.java.
References model.Pen.setCustom().
Referenced by model.SlogoModel.initializePenColor().
void model.Turtle.setShape (Image image)
Set the shape of the turtle.
Parameters
image Image of the turtle
Definition at line 107 of file Turtle.java.
Referenced by view.SettingsView.addTurtleChoices(), and instructions.commands.SetShape.execute().
void model.Turtle.setTurtleInfo () private
Set the turtle info and show the xy coordinate and angle at Tooltip.
Definition at line 323 of file Turtle.java.
References model.Turtle.getAngle().
Referenced by model.Turtle.clear(), model.Turtle.moveTurtleAndDrawLine(), model.Turtle.rotate(), model.Turtle.setCoordinates(), and model.Turtle.Turtle().
void model.Turtle.setVisible (boolean state)
Set the turtle visible or not.
Parameters
state if the turtle is visible
Definition at line 154 of file Turtle.java.
Referenced by instructions.commands.HideTurtle.execute(), instructions.commands.ShowTurtle.execute(), and model.Turtle.toggleVisible().
void model.Turtle.stampImage ()
Stamp the turtle image.
Definition at line 166 of file Turtle.java.
References model.TurtleAbstract.DEFAULT_TURTLE_SIZE.
Referenced by instructions.commands.Stamp.execute().
void model.Turtle.toggleVisible ()
Set the toggle grid visible.
Definition at line 382 of file Turtle.java.
References model.Turtle.setVisible().
Referenced by model.SlogoModel.toggleTurtle().
Member Data Documentation
final int model.Turtle._10 = 10 static private
Definition at line 26 of file Turtle.java.
final double model.Turtle._10_0 = 10.0 static private
Definition at line 24 of file Turtle.java.
Referenced by model.Turtle.getAngle().
final int model.Turtle.FULL_CIRCLE_DEGREE = 360 static private
Definition at line 28 of file Turtle.java.
Referenced by model.Turtle.calculateAngle().
boolean model.Turtle.isVisible private
Definition at line 48 of file Turtle.java.
double model.Turtle.myAngle = DEFAULT_TURTLE_ANGLE private
Definition at line 37 of file Turtle.java.
double [] model.Turtle.myCoordinates = { DEFAULT_XCOORDINATE, DEFAULT_YCOORDINATE } private
Definition at line 34 of file Turtle.java.
Image model.Turtle.myDefaultOff private
Initial value:
= new Image(getClass().getResourceAsStream(
            DEFAULT_OFF_IMAGE))
Definition at line 46 of file Turtle.java.
Image model.Turtle.myDefaultOn private
Initial value:
= new Image(getClass().getResourceAsStream(
            DEFAULT_ON_IMAGE))
Definition at line 44 of file Turtle.java.
Group model.Turtle.myDrawing private
Definition at line 39 of file Turtle.java.
Referenced by model.Turtle.generate(), and model.Turtle.getDrawing().
ImageView model.Turtle.myImage private
Definition at line 32 of file Turtle.java.
Referenced by model.Turtle.getTurtleImg().
Group model.Turtle.myLines private
Definition at line 40 of file Turtle.java.
Pen model.Turtle.myPen private
Definition at line 38 of file Turtle.java.
Referenced by model.Turtle.getPen().
double [] model.Turtle.myRelativeCoordinates private
Initial value:
= { DEFAULT_REALATIVE_COORDINATE,
            DEFAULT_REALATIVE_COORDINATE }
Definition at line 35 of file Turtle.java.
Referenced by model.Turtle.getCoordinates().
Group model.Turtle.myStamps private
Definition at line 41 of file Turtle.java.
boolean model.Turtle.myState = true private
Definition at line 49 of file Turtle.java.
Referenced by model.Turtle.changeState().
Tooltip model.Turtle.myTurtleInfo private
Definition at line 43 of file Turtle.java.
ObservableList<Image> model.Turtle.myTurtleShapes private
Definition at line 33 of file Turtle.java.
Referenced by model.Turtle.getShapeList().
final long model.Turtle.serialVersionUID = 3491015094836744017L static private
Definition at line 30 of file Turtle.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/model/Turtle.java