slogo_team02: view.DataViewComponents Class Reference
view.DataViewComponents Class Reference abstract
Public Member Functions
DataViewComponents (InputView input, double width, double height)
Public Member Functions inherited from view.ScrollView
ScrollView ()
ScrollView (InputView input, double width, double height)
void setView (double width, double height)
void addTextBox (String s)
Protected Member Functions
void addTextBoxWithDeleteButton (String s, Feature f)
Protected Member Functions inherited from view.ScrollView
Text makeClickableText (String s)
Private Member Functions
Button makeDeleteButton (String s, Feature f)
Static Private Attributes
static final int DELETE_BUTTON_X = 50
Additional Inherited Members
Protected Attributes inherited from view.ScrollView
VBox myView
Detailed Description
Abstract class used construct the dataview subcomponents.
Author
Kevin Li
Definition at line 16 of file DataViewComponents.java.
Constructor & Destructor Documentation
view.DataViewComponents.DataViewComponents (InputView input, double width, double height)
Definition at line 19 of file DataViewComponents.java.
Member Function Documentation
void view.DataViewComponents.addTextBoxWithDeleteButton (String s, Feature f) protected
Creates a text box with delete buttons to be added to the view.
Parameters
s The string to be displayed in the textbox.
f The feature that things are to be deleted from in the model.
Definition at line 28 of file DataViewComponents.java.
References view.DataViewComponents.makeDeleteButton(), and view.ScrollView.myView.
Referenced by view.VariablesView.update(), and view.UDCommandsView.update().
Button view.DataViewComponents.makeDeleteButton (String s, Feature f) private
Makes a delete button.
Parameters
s The string representation of the variable or command.
f The feature to delete data from.
Returns
Delete button
Definition at line 42 of file DataViewComponents.java.
References view.ScrollView.myView, and model.Feature.remove().
Referenced by view.DataViewComponents.addTextBoxWithDeleteButton().
Member Data Documentation
final int view.DataViewComponents.DELETE_BUTTON_X = 50 static private
Definition at line 17 of file DataViewComponents.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/DataViewComponents.java