slogo_team02: view.InputView Class Reference
view.InputView Class Reference
Public Member Functions
InputView (SlogoModel model, double width, double height, Locale locale)
void addAndShowText (String text)
Public Member Functions inherited from view.PaneView
void setView (double width, double height)
Public Attributes
HBox myView
Static Public Attributes
static final String DEFAULT_DISPLAY_RESOURCE = "resources.languages/Display"
Private Member Functions
void initInputArea (double width, double height)
void initSubmitButton (double width, double height)
Private Attributes
TextArea myInput
Button mySubmitButton
SlogoModel myModel
String myText = ""
Locale myLocale
Static Private Attributes
static final double HEIGHT_RATIO =0.25
static final double INPUTAREA_WIDTH_RATIO =0.875
static final double BUTTON_WIDTH_RATIO =0.125
Detailed Description
Area to inputCommands.
Author
Kevin Li
Meng'en Huang
Definition at line 20 of file InputView.java.
Constructor & Destructor Documentation
view.InputView.InputView (SlogoModel model, double width, double height, Locale locale)
Definition at line 36 of file InputView.java.
References view.InputView.initInputArea(), view.InputView.initSubmitButton(), and view.PaneView.setView().
Member Function Documentation
void view.InputView.addAndShowText (String text)
Shows text onto the input view.
Parameters
text
Definition at line 99 of file InputView.java.
Referenced by view.ScrollView.makeClickableText().
void view.InputView.initInputArea (double width, double height) private
Initializes the dimensions of the input area.
Parameters
width width of the entire program
height height of the entire program
Definition at line 57 of file InputView.java.
Referenced by view.InputView.InputView().
void view.InputView.initSubmitButton (double width, double height) private
Creates the submit button and sets it to be the correct size.
Parameters
width Width of the program.
height Height of the program.
Definition at line 70 of file InputView.java.
References model.SlogoModel.parseAndExecute().
Referenced by view.InputView.InputView().
Member Data Documentation
final double view.InputView.BUTTON_WIDTH_RATIO =0.125 static private
Definition at line 25 of file InputView.java.
final String view.InputView.DEFAULT_DISPLAY_RESOURCE = "resources.languages/Display" static
Definition at line 22 of file InputView.java.
final double view.InputView.HEIGHT_RATIO =0.25 static private
Definition at line 23 of file InputView.java.
final double view.InputView.INPUTAREA_WIDTH_RATIO =0.875 static private
Definition at line 24 of file InputView.java.
TextArea view.InputView.myInput private
Definition at line 30 of file InputView.java.
Locale view.InputView.myLocale private
Definition at line 34 of file InputView.java.
SlogoModel view.InputView.myModel private
Definition at line 32 of file InputView.java.
Button view.InputView.mySubmitButton private
Definition at line 31 of file InputView.java.
String view.InputView.myText = "" private
Definition at line 33 of file InputView.java.
HBox view.InputView.myView
Definition at line 29 of file InputView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/InputView.java