slogo_team02: view.HistoryResultsView Class Reference
view.HistoryResultsView Class Reference
Public Member Functions
HistoryResultsView (InputView input, double width, double height, Locale locale)
void update (List< String > history, String result)
Public Member Functions inherited from view.PaneView
void setView (double width, double height)
Private Attributes
HistoryView myHistory
ResultsView myResults
VBox myView
Locale myLocale
Static Private Attributes
static final String DEFAULT_DISPLAY_RESOURCE = "resources.languages/Display"
static final double WIDTH_RATIO =0.2
static final double HEIGHT_RATIO =0.6875
static final double HISTORYVIEW_HEIGHT_RATIO =0.666667
static final double RESULTVIEW_HEIGHT_RATIO =0.166667
static final double TITLEDPANE_WIDTH_RATIO =0.166667
static final double TITLEDPANE_HEIGHT_RATIO =0.6875
Detailed Description
Visual Component containing the subcomponents that displays the history and the calculated results.
Author
Kevin Li
Mengen Huang
Definition at line 17 of file HistoryResultsView.java.
Constructor & Destructor Documentation
view.HistoryResultsView.HistoryResultsView (InputView input, double width, double height, Locale locale)
Initiate the History Results View.
Parameters
input Input View
width width of the view
height height of the view
locale language and locale the view uses
Definition at line 42 of file HistoryResultsView.java.
References view.HistoryResultsView.myHistory, and view.HistoryResultsView.myResults.
Member Function Documentation
void view.HistoryResultsView.update (List< String > history, String result)
Calls the update function in the subcomponents in order to update the view based off model data.
Parameters
history List of the runnable history that has been entered into the input area.
result The result from the last instruction.
Definition at line 78 of file HistoryResultsView.java.
References view.HistoryView.update(), and view.ResultsView.update().
Referenced by view.SlogoWindow.update().
Member Data Documentation
final String view.HistoryResultsView.DEFAULT_DISPLAY_RESOURCE = "resources.languages/Display" static private
Definition at line 19 of file HistoryResultsView.java.
final double view.HistoryResultsView.HEIGHT_RATIO =0.6875 static private
Definition at line 21 of file HistoryResultsView.java.
final double view.HistoryResultsView.HISTORYVIEW_HEIGHT_RATIO =0.666667 static private
Definition at line 22 of file HistoryResultsView.java.
HistoryView view.HistoryResultsView.myHistory private
Definition at line 30 of file HistoryResultsView.java.
Referenced by view.HistoryResultsView.HistoryResultsView().
Locale view.HistoryResultsView.myLocale private
Definition at line 33 of file HistoryResultsView.java.
ResultsView view.HistoryResultsView.myResults private
Definition at line 31 of file HistoryResultsView.java.
Referenced by view.HistoryResultsView.HistoryResultsView().
VBox view.HistoryResultsView.myView private
Definition at line 32 of file HistoryResultsView.java.
final double view.HistoryResultsView.RESULTVIEW_HEIGHT_RATIO =0.166667 static private
Definition at line 23 of file HistoryResultsView.java.
final double view.HistoryResultsView.TITLEDPANE_HEIGHT_RATIO =0.6875 static private
Definition at line 25 of file HistoryResultsView.java.
final double view.HistoryResultsView.TITLEDPANE_WIDTH_RATIO =0.166667 static private
Definition at line 24 of file HistoryResultsView.java.
final double view.HistoryResultsView.WIDTH_RATIO =0.2 static private
Definition at line 20 of file HistoryResultsView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/HistoryResultsView.java