slogo_team02: view.TurtleView Class Reference
view.TurtleView Class Reference
Public Member Functions
TurtleView (double width, double height)
void toggleGrid ()
void changeColor (Color color)
void update (Node node)
Public Member Functions inherited from view.PaneView
void setView (double width, double height)
Private Member Functions
Group makeGrid (double width, double height)
Private Attributes
Group myGrid
Group myLines
Static Private Attributes
static final long serialVersionUID = -6613430284719479884L
static final int GRIDLINE_INTERVAL = 20
static final double VIEW_HEIGHT_RATIO = 0.6875
static final double VIEW_WIDTH_RATIO = 0.6
Detailed Description
Component of SlogoWindow which shows turtle, lines, and grid.
Author
Kevin Li
Definition at line 18 of file TurtleView.java.
Constructor & Destructor Documentation
view.TurtleView.TurtleView (double width, double height)
The view in the center of the window with black background. Show the action of turtle, the lines drawn, and toggle whether or not to show the "reference" grid in light gray.
Parameters
width width of TurtleView
height height of TurtleView
Definition at line 34 of file TurtleView.java.
References view.TurtleView.makeGrid(), and view.PaneView.setView().
Member Function Documentation
void view.TurtleView.changeColor (Color color)
Change the background color of the TurtleView.
Parameters
color background color
Definition at line 78 of file TurtleView.java.
Referenced by view.SettingsView.addBGColorPicker(), and view.SlogoWindow.update().
Group view.TurtleView.makeGrid (double width, double height) private
Make the "reference" grid.
Parameters
width width of TurtleView
height height of TurtleView
Returns
Groups of light gray lines which consists of "reference" grid
Definition at line 48 of file TurtleView.java.
References view.TurtleView.GRIDLINE_INTERVAL.
Referenced by view.TurtleView.TurtleView().
void view.TurtleView.toggleGrid ()
If the grid is on, turn it off; if not, turn it on.
Definition at line 66 of file TurtleView.java.
Referenced by view.SettingsView.addButtons().
void view.TurtleView.update (Node node)
Update as part of Observer. Update when the Observable data changes
Parameters
node Node contains turtle, lines and stamp, passed from Turtle in model package
Definition at line 88 of file TurtleView.java.
Referenced by view.SlogoWindow.update().
Member Data Documentation
final int view.TurtleView.GRIDLINE_INTERVAL = 20 static private
Definition at line 21 of file TurtleView.java.
Referenced by view.TurtleView.makeGrid().
Group view.TurtleView.myGrid private
Definition at line 24 of file TurtleView.java.
Group view.TurtleView.myLines private
Definition at line 25 of file TurtleView.java.
final long view.TurtleView.serialVersionUID = -6613430284719479884L static private
Definition at line 20 of file TurtleView.java.
final double view.TurtleView.VIEW_HEIGHT_RATIO = 0.6875 static private
Definition at line 22 of file TurtleView.java.
final double view.TurtleView.VIEW_WIDTH_RATIO = 0.6 static private
Definition at line 23 of file TurtleView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/TurtleView.java