slogo_team02: view.MenuView Class Reference
view.MenuView Class Reference
Public Member Functions
MenuView (Locale locale, TabPane tabs, double width, double height)
Static Public Attributes
static final String DEFAULT_MENU_RESOURCE = "resources.languages/Menu"
Package Attributes
TabPane myTabs
Private Member Functions
void setMap ()
void createFileMenu (Locale locale, double width, double height)
void getLocale (Menu menuLanguage)
MenuItem makeLanguageItem (String language)
void setFile (Locale locale, double width, double height, Menu menuFile)
void openFile (Locale locale, double width, double height, Menu menuFile)
void saveFile (Locale locale, double width, double height, Menu menuFile)
void newFile (Locale locale, double width, double height, Menu menuFile)
void setView (double width, double height)
void clear ()
Private Attributes
int myTabCount
FileChooser myFileChooser
Locale myLocale
Map< String, Locale > localeMap = new HashMap<String, Locale>()
double myWidth
double myHeight
ResourceBundle languageBundle
Static Private Attributes
static final double HEIGHT_RATIO = 0.0625
static final double ADDITIONAL_WINDOW_HEIGHT_RATIO = 0.9
Detailed Description
The over-arching menu bar which enables the user to create new file, open saved file, save file, and choose among the language.
Author
Kevin Li
Mengen Huang
Definition at line 32 of file MenuView.java.
Constructor & Destructor Documentation
view.MenuView.MenuView (Locale locale, TabPane tabs, double width, double height)
Create the MenuView , set up menuItems and set up the localeMap.
Parameters
locale
tabs
width
height
Definition at line 58 of file MenuView.java.
References view.MenuView.createFileMenu(), view.MenuView.setMap(), and view.MenuView.setView().
Member Function Documentation
void view.MenuView.clear () private
Clear the Menu.
Definition at line 267 of file MenuView.java.
Referenced by view.MenuView.makeLanguageItem().
void view.MenuView.createFileMenu (Locale locale, double width, double height) private
Create the Menu.
Parameters
locale languaeg and locale applied
width width of the view
height height of the view
Definition at line 91 of file MenuView.java.
References view.MenuView.getLocale(), and view.MenuView.setFile().
Referenced by view.MenuView.makeLanguageItem(), and view.MenuView.MenuView().
void view.MenuView.getLocale (Menu menuLanguage) private
Add in MenuItems to enable the user to choose from the language and change the locale.
Parameters
menuLanguage Menu to choose language
Definition at line 106 of file MenuView.java.
References view.MenuView.makeLanguageItem().
Referenced by view.MenuView.createFileMenu().
MenuItem view.MenuView.makeLanguageItem (String language) private
Method to change the menu and pass in the new locale after user changes. the language option
Parameters
language String that represents the language name
Returns
the MenuItem shown on the menu
Definition at line 119 of file MenuView.java.
References view.MenuView.clear(), and view.MenuView.createFileMenu().
Referenced by view.MenuView.getLocale().
void view.MenuView.newFile (Locale locale, double width, double height, Menu menuFile) private
Create a new tab and load in a new Slogo Window with view and model.
Parameters
locale current language and locale
width width of the view
height height of the view
menuFile the File Menu where the Menu Item is listed
Definition at line 230 of file MenuView.java.
Referenced by view.MenuView.setFile().
void view.MenuView.openFile (Locale locale, double width, double height, Menu menuFile) private
Open the new file and loaded in the saved state of the Slogo window.
Parameters
locale current language and locale
width width of the view
height height of the view
menuFile the File Menu where the Menu Item is listed
Definition at line 155 of file MenuView.java.
Referenced by view.MenuView.setFile().
void view.MenuView.saveFile (Locale locale, double width, double height, Menu menuFile) private
Save state of the Slogo window.
Parameters
locale current language and locale
width width of the view
height height of the view
menuFile the File Menu where the Menu Item is listed
Definition at line 196 of file MenuView.java.
Referenced by view.MenuView.setFile().
void view.MenuView.setFile (Locale locale, double width, double height, Menu menuFile) private
Set all the MenuItems in the File Menu.
Parameters
locale current language and locale
width width of the veiw
height height of the view
menuFile the File Menu all the Menu Item are listed
Definition at line 141 of file MenuView.java.
References view.MenuView.newFile(), view.MenuView.openFile(), and view.MenuView.saveFile().
Referenced by view.MenuView.createFileMenu().
void view.MenuView.setMap () private
Set up the localeMap.
Definition at line 79 of file MenuView.java.
Referenced by view.MenuView.MenuView().
void view.MenuView.setView (double width, double height) private
Set up the size of the view.
Parameters
width width of the view
height height of the view
Definition at line 259 of file MenuView.java.
Referenced by view.MenuView.MenuView().
Member Data Documentation
final double view.MenuView.ADDITIONAL_WINDOW_HEIGHT_RATIO = 0.9 static private
Definition at line 36 of file MenuView.java.
final String view.MenuView.DEFAULT_MENU_RESOURCE = "resources.languages/Menu" static
Definition at line 38 of file MenuView.java.
final double view.MenuView.HEIGHT_RATIO = 0.0625 static private
Definition at line 34 of file MenuView.java.
ResourceBundle view.MenuView.languageBundle private
Definition at line 49 of file MenuView.java.
Map<String, Locale> view.MenuView.localeMap = new HashMap<String, Locale>() private
Definition at line 45 of file MenuView.java.
FileChooser view.MenuView.myFileChooser private
Definition at line 42 of file MenuView.java.
double view.MenuView.myHeight private
Definition at line 48 of file MenuView.java.
Locale view.MenuView.myLocale private
Definition at line 44 of file MenuView.java.
int view.MenuView.myTabCount private
Definition at line 41 of file MenuView.java.
TabPane view.MenuView.myTabs package
Definition at line 40 of file MenuView.java.
double view.MenuView.myWidth private
Definition at line 47 of file MenuView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/MenuView.java