slogo_team02: view.ScrollView Class Reference
view.ScrollView Class Reference abstract
Public Member Functions
ScrollView ()
ScrollView (InputView input, double width, double height)
void setView (double width, double height)
void addTextBox (String s)
Protected Member Functions
Text makeClickableText (String s)
Protected Attributes
VBox myView
Private Attributes
InputView myInput
Static Private Attributes
static final double VIEW_HEIGHT_RATIO = 0.6875
static final double VIEW_WIDTH_RATIO = 0.2
static final int INSTRUCTION_FONT_SIZE = 12
Detailed Description
The abstract class which is the super class of HistoryResults View and DataView class.
Author
Mengen Huang
Kevin Li
Definition at line 18 of file ScrollView.java.
Constructor & Destructor Documentation
view.ScrollView.ScrollView ()
Definition at line 26 of file ScrollView.java.
view.ScrollView.ScrollView (InputView input, double width, double height)
Set up the ScrollView.
Parameters
input InputView
width width of the view
height height of the view
Definition at line 35 of file ScrollView.java.
References view.ScrollView.setView().
Member Function Documentation
void view.ScrollView.addTextBox (String s)
Take in a string and add the String as a HBox.
Parameters
s String displayed
Definition at line 57 of file ScrollView.java.
References view.ScrollView.makeClickableText().
Referenced by view.HistoryView.update(), and view.BasicCommandsView.update().
Text view.ScrollView.makeClickableText (String s) protected
Take in a string and make it into a clickable Text.
Parameters
s String displayed
Returns
the clickable text
Definition at line 69 of file ScrollView.java.
References view.InputView.addAndShowText().
Referenced by view.ScrollView.addTextBox().
void view.ScrollView.setView (double width, double height)
Set up the size of the view.
Parameters
width width of the view
height height of the view
Definition at line 47 of file ScrollView.java.
Referenced by view.ScrollView.ScrollView().
Member Data Documentation
final int view.ScrollView.INSTRUCTION_FONT_SIZE = 12 static private
Definition at line 22 of file ScrollView.java.
InputView view.ScrollView.myInput private
Definition at line 23 of file ScrollView.java.
VBox view.ScrollView.myView protected
Definition at line 24 of file ScrollView.java.
Referenced by view.DataViewComponents.addTextBoxWithDeleteButton(), view.DataViewComponents.makeDeleteButton(), view.HistoryView.update(), view.VariablesView.update(), view.BasicCommandsView.update(), and view.UDCommandsView.update().
final double view.ScrollView.VIEW_HEIGHT_RATIO = 0.6875 static private
Definition at line 20 of file ScrollView.java.
final double view.ScrollView.VIEW_WIDTH_RATIO = 0.2 static private
Definition at line 21 of file ScrollView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team02/repository/src/view/ScrollView.java